# Site
repository: DougTrajano/dougresume
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Douglas Trajano
title: Data Scientist
email: douglas.trajano@outlook.com
# email_title: Email (Email title override)
phone: +55 51 981988339
# phone_title: Phone (Phone title override)
website: https://dougtrajano.github.io/resume/
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: doug_trajano
github_username:  DougTrajano
stackoverflow_username: "8803008"
#dribbble_username: jekyll
facebook_username: DougTrajano
#flickr_username: jekyll
instagram_username: dougtrajano
linkedin_username: douglas-trajano
#xing_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
#googleplus_username: +jekyll
#orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: WhatsApp
  icon: fab fa-whatsapp
  url: https://wa.me/5551981988339
- title: Kaggle
  icon: fab fa-kaggle
  url: https://www.kaggle.com/dougtrajano

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/doug_profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi! I'm Douglas, 27 years old and I live in Canoas, RS, Brazil.

  I'm a data scientist with two years of experience developing amazing <mark>Data Products</mark> and <mark>researches</mark>.
    
  Implementing NLP models, recommendation models, analysis, researches, experiments and A/B tests for customer service.

  As member of the Data Science chapter, I helped define several data science processes used by data scientists across Sicredi (eg. Model Cards, documentations, etc.).

  In my free time, I'm a <mark>CS:GO</mark> and <mark>Age of Empires</mark> player. :)

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Project name
        link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        link_text: Link Text
        additional_links:
          - title:  Github page for project (eg. sproogen/modern-resume-theme)
            icon: fab fa-github
            url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
          - title:  Github page for project (eg. sproogen/modern-resume-theme)
            icon: fab fa-github
            url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        quote: >
          Short overview of the project (optional)
        description: | # this will include new lines to allow paragraphs
          Description about the work on/with the project
  - title: Experience
    layout: list
    content:
      - layout: right
        title: Company name
        sub_title: Job title
        caption: Date Range (eg. November 2016 - present)
        link: Link to company (optional)
        quote: >
          Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          Description of role
  - title: Education
    layout: list
    content:
      - layout: top-right
        title: Institution name
        sub_title: Qualifications (eg. BA Performing Arts)
        caption: Date Range (eg. 2016 - 2019)
        quote: >
          Short institution or course description (optional)
        description: | # this will include new lines to allow paragraphs
          Description of qualification
  - title: Certifications
    layout: text
    content: | # this will include new lines to allow paragraphs
      - Microsoft Certified: Azure Data Scientist Asccoaite <mark>Azure Cloud</mark>
      - AWS Certified Machine Learning - Specialty <mark>AWS</mark>
      - Certified Associate in Project Management (CAPM)® <mark>PMI</mark>
      - ITIL® Foundation Certificate in IT Service Management <mark>EXIN</mark>
      - MCP (70-687) - Configuring Windows 8.1 <mark>Microsoft</mark>
      - Social Media and Community (SMaC) Certification <mark>Dell</mark>
  - title: Courses
    layout: text
    content: | # this will include new lines to allow paragraphs
      **Relevant Courses**
      - Deep Learning Specialization - [deeplearning.ai](https://www.deeplearning.ai/) <mark>Coursera</mark>
      - Machine Learning - [Stanford University](https://www.stanford.edu/) <mark>Coursera</mark>
      - Probability and Statistics: To p or not to p? - [University of London](https://london.ac.uk/) <mark>Coursera</mark>
      - Data Science Math Skills - [Duke University](https://duke.edu/) <mark>Coursera</mark>
      - Creative Thinking: Techniques and Tools for Success - [Imperial College London](https://www.imperial.ac.uk/) <mark>Coursera</mark>
      - Successful Negotiation: Essential Strategies and Skills - [University of Michigan](https://umich.edu/) <mark>Coursera</mark>

      **Others Courses**
      - eXtreme Programming (XP) <mark>TreinaWeb</mark>
      - Design Thinking <mark>TreinaWeb</mark>
      - Tableau for Data Scientists <mark>Udemy</mark>
      - Power BI <mark>Udemy</mark>
      - Python for Data Science and Machine Learning <mark>Udemy</mark>
      - REST APIs with Python and Flask <mark>Udemy</mark>
      - MongoDB Developer <mark>TreinaWeb</mark>
      - MySQL DBA <mark>TreinaWeb</mark>
      - MySQL Developer <mark>TreinaWeb</mark>
      - Oracle Developer <mark>TreinaWeb</mark>

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
